### ISSUE TITLE
Windows environment escape bug in intermediary generated files

### ISSUE THREAD

**Issue by odhs** [leaanthony/mewn#7]
When mewn generates the intermediary files the filepaths are not escaping. 

Desired results (With double bars):
```
func init() {
	mewn.AddAsset("../../ui/html", "F:\\DOCUMENTS\\GO_PATH\\   ( continues ...)
```

Current results (With only a bar):
```
func init() {
	mewn.AddAsset("../../ui/html", "F:\DOCUMENTS\GO_PATH\   ( continues ...)
```

I can't build with the current version. Go shows the errors:
cmd\web\main-mewn.go:8:38: unknown escape sequence
cmd\web\main-mewn.go:8:79: non-hex character in escape sequence: i

Thank you in Advance!

**Comment by leaanthony** [comment]
Thanks for raising this. I'm surprised - it's being used on windows just fine in https://github.com/wailsapp/wails. I'll have a look.

**Comment by odhs** [comment]
If you need my code I to analyse I send to you, no problems. 

On my local respository I fix editing:  `lib\pack.go line:52`
`result += fmt.Sprintf("  mewn.AddAsset(\"%s\", %q, \"%s\")\n", group.LocalPath, localPath, packedData)`

Changing `\"%s\"` to `%q`

But I not sure if this is a good way to fix this. Well...
Changing this the command line `mewn build` works!
Then I tried the command line `mewn pack` and I receive an error.

I use **git-bash** to command line in Windows then:

```sh
$ mewn pack ./cmd/web/
Mewn
Error running command! %!s(func() string=0x4f4430)
From program: can't load package: package -ldflags is not in GOROOT (c:\go\src\-ldflags)
can't load package: package -w -s is not in GOROOT (c:\go\src\-w -s)
```

Then I discovered that it is not possible to compile the way I used to: `go build ./cmd /web`
But no problem, I found that if I enter the directory it is possible to build normally.. =)
So:

```sh
$ cd cmd
$ cd web
$ mewn pack
```

But something was still missing. Put the SqLite flag (`--tags sqlite_userauth`) in the command.
So I found the best way to compile with mewn like this:

`mewn build -ldflags "-s -w -H=windowsgui" --tags sqlite_userauth`

I`m happy with the results. I love your package mewn!

I used it in my templates directory.
Now the next step is replace the static directory source of the FileServer:
`fileServer := http.FileServer(http.Dir("./ui/static/"))`

Thank you in advance.

**Comment by leaanthony** [comment]
Thanks for your feedback! %q seems like a safe option but would need more testing. Out of interest, if you use forward slashes, even on windows, does it work with the standard code?

**Comment by odhs** [comment]
> Thanks for your feedback! %q seems like a safe option but would need more testing. Out of interest, if you use forward slashes, even on windows, does it work with the standard code?

Yes, forward slashes works too.

**Comment by leaanthony** [comment]
Yeah, so i think it was built with forward slashes in mind. I'll check out the PR :+1:

**Comment by leaanthony** [comment]
I've updated master with a fix. If this works for you (it's basically your change!) I'll look to tag it.

**Comment by odhs** [comment]
Thank you!
I think this issue has been solved.
You can close it if you wish.
